### ISSUE TITLE
Make it work on PHP 5.5 or provide work-around?

### ISSUE THREAD

**Issue by OscarEriksen** [intercom/intercom-php#146]
Hi,

We can't update our server platform right now but are in immediate need to track events in the backend. We run PHP 5.5 on an IIS-platform. 

My main question is: how can we and/or you fix this and create a work around?

## Version info
  - intercom-php version: 2.0.0
  - PHP version: 5.5

## Expected behavior
- It should work and not give an error message.

## Actual behavior
Halts with PHP error: 
`Parse error: syntax error, unexpected 'function' (T_FUNCTION), expecting identifier (T_STRING) or \\ (T_NS_SEPARATOR) in C:\inetpub\yyy\vendor\intercom\intercom-php\src\IntercomClient.php on line 7`

## Steps to reproduce
 1. Use PHP 5.5
 2. Follow the intended installation with composer and usage
 3. Look at the error message

**Comment by xewl** [comment]
Idem on nginx & PHP Version 5.5.9-1ubuntu4.17

The ``use function`` on line 7 in IntercomClient is not compatible.
Shouldn't there be a way to call the ``stream_for`` function otherwise?

**Comment by dannyfallon** [comment]
Hi there :wave: As per [Bob's comment on a PR adding support for PHP 5.5](https://github.com/intercom/intercom-php/pull/147#issuecomment-233319564) we've taken the decision to not do this because PHP 5.5 is no longer officially support and is End of Life since July 10th. There are other third party, community supported libraries such as https://packagist.org/packages/gayanhewa/intercom-php that allow the use of older PHP versions with Intercom.
