### ISSUE TITLE
Missing company->update() method

### ISSUE THREAD

**Issue by donaldwasserman** [intercom/intercom-php#180]
This is somewhat of a trivial issue, but for some reason it really bothered me this morning (for reasons that have 0% due to intercom). 

The intercom documentation outlines an `updateCompany()` method. Even though it doesn't do anything differently than the `createCompany` method. This just adds a totally unnecessary code that does the same thing. 

Just wanted to know if this was intentionally left out or just an oversite. I submitted a PR as well.
## Version info
- intercom-php version: 3.1
- PHP version: 5.6
## Expected behavior

have an update company option
## Actual behavior

no option to update company

**Comment by Skaelv** [comment]
As you already know create and update uses the same endpoint which is why we didn't want to override our SDKs in the first place with alias methods. 

Since it seems to create confusion we'll add those update methods for companies/users and leads.
 Thanks for the PR @donaldwasserman and sorry it took so long to merge.
