### ISSUE TITLE
Calling getUsers throws a 409 when duplicate profiles exist in intercom with same email

### ISSUE THREAD

**Issue by arimai** [intercom/intercom-php#273]
## Version info
  - intercom-php version: 4.0.1
  - PHP version: 7.2.13

## Expected behavior
I expected this [line](https://github.com/intercom/intercom-php/blob/362e3053d741d96fe56de6ad156885ea564dd884/src/IntercomUsers.php#L59) to make an API call such as `https://api.intercom.io/users?email=<email-with-more-than-one-user>` which should ideally return a list of users and their details that exist for the same email in intercom.

## Actual behavior
I get a `409 Multiple existing users` error message. Even though the api call seems to be right. Here is the exact error message:

```
Http/Client/Exception/HttpException with message 'Client error: `GET https://api.intercom.io/users?email=<email>` resulted in a `409 Conflict` response:
{"type":"error.list","request_id":"001n2v63prh02g8hv120","errors":[{"code":"conflict","message":"Multiple existing users (truncated...)
```
Another important thing to note here is that when I use curl or Postman to do the API request it works seamlessly. 

## Steps to reproduce (as granular as possible, including screenshots where appropriate)
 1. Have more than one user with the same email in intercom
 2. Call getUsers with $options set as `'email' => <insert-email-here>`
 3. Verify that you get a 409 instead of getting an array with list of users. Check this to know what to expect: https://developers.intercom.com/intercom-api-reference/reference#list-by-email-1

## Logs
```
Http/Client/Exception/HttpException with message 'Client error: `GET https://api.intercom.io/users?email=<email>` resulted in a `409 Conflict` response:
{"type":"error.list","request_id":"001n2v63prh02g8hv120","errors":[{"code":"conflict","message":"Multiple existing users (truncated...)
```

**Comment by GabrielAnca** [comment]
Hi @arimai 👋 Thanks for sharing this issue with us!

The issue you mention is an existing limitation in the Intercom API version 1.0. From version 1.1 onward, it is possible to list users when more than one of them has the same email. You can see the full explanation [in the API changelog](https://developers.intercom.com/building-apps/docs/api-changelog).

You can either update your default API Version in the [Developer Hub](https://developers.intercom.com/), or you can initialize this client passing a specific Intercom API-Version header (`$client = new IntercomClient('<insert_token_here>', null, ['Intercom-Version' => '1.1']);`). You can see the full information in our documentation about [API Versioning](https://developers.intercom.com/building-apps/docs/api-versioning).

I imagine you get different results with curl and Postman because our official examples always send the version 1.1 header.

I'll close this issue, but please feel free to reopen it if you are still experiencing this issue with version 1.1.

**Comment by danlafreniere** [comment]
Thank you @GabrielAnca! I'll be sure to check that today :D
