### ISSUE TITLE
Unable to update beyond 4.0.0 without downgrading HTTPlug 2

### ISSUE THREAD

**Issue by funkjedi** [intercom/intercom-php#279]
https://github.com/intercom/intercom-php/blob/d7d51068d9362730992eb5dfa357fdb620da4dc3/composer.json#L30
4.0.1 added php-http/client-common:^1.9 which only allows httplug 1. This effectively prevents using updating to 4.0.1 or beyond without downgrade httplug 2 to httplug 1.

**Comment by GabrielAnca** [comment]
Hey @funkjedi 👋  thank you for reporting this! If I remember correctly, at the moment we implemented HTTPlug, client-common was not compatible with HTTPlug version 2.

If you have some time and want to make a PR that makes it compatible with versions 1 and 2 (not sure if that's possible), that would be very welcome! Otherwise I can try to have a look at this 😃

**Comment by GabrielAnca** [comment]
The last PR from @tyloo enabled support for HTTPlug 2. You should be able to use this SDK with the new version `4.0.3` 😃 It might take a while to show up in Packagist though
