### ISSUE TITLE
[Feature] Use type hint for methods

### ISSUE THREAD

**Issue by sylfabre** [intercom/intercom-php#282]
Symfony4's auto-wiring feature requires type hint on constructors to work.

For instance `\Intercom\IntercomUsers::__construct($client)` should become `\Intercom\IntercomUsers::__construct(IntercomClient $client)`.

**Comment by GabrielAnca** [comment]
Hi @sylfabre 👋 thanks for opening this issue!

I am wondering why you would need to use the `IntercomUsers` class directly rather than `$intercomClient->users`.

The main reason for my question is because as far as I know, you wouldn't be able to autowire `IntercomClient` anyway because it needs your token, so even if we make `IntercomUsers` _autowirable_, you would still need to define the service for `IntercomClient` manually in your `services.yaml` file. Please correct me if I'm wrong, I didn't use Symfony a lot since version 4 was launched.

Those are just my questions about your use case. I think adding the types to the constructors would definitely be a good idea, especially now that all the current PHP versions support it. Feel free to create a PR for that if you have time for it 😃

**Comment by sylfabre** [comment]
@GabrielAnca I use `IntercomUsers` class directly because it's easier to mock only this than both `IntercomClient` and `IntercomUsers` when I use phpunit.

Yes you're right, I still need to define the service because of the token. But with SF4 autowiring, I can only define scalar arguments of the constructor. So using type hinting makes me write less code

**Comment by sylfabre** [comment]
@GabrielAnca here is my PR: https://github.com/intercom/intercom-php/pull/284

**Comment by GabrielAnca** [comment]
Makes sense, thank you for sharing that! It helps us understand how the SDK is used and how it could be improved in the future 😃 And also thanks for the PR! I'll release a new version so you can leverage it immediately
