### ISSUE TITLE
HTTP 409 on Update Customer

### ISSUE THREAD

**Issue by MCKLtech** [intercom/intercom-php#290]
## Version info
  - intercom-php version: 4.2.0
  - PHP version: 7.3.10

## Expected behavior

We're using the following code to create/update a customer and assign them a company. The variables are valid. **company_id** is our ID for the given company. The user may or may not already exist.

`$client = new IntercomClient(env('INTERCOM_TOKEN', false));

$user = $client->users->update([
    
    "email" => $owner->email,
            
    "name" => $owner->name,
            
    "companies" => [
                
    [
        "company_id" => $event->team->id,
        "name" => $event->team->name
                
    ]
                
    ]
]);`

If we remove the companies information, the error persists.

## Actual behaviour

The following error is observed:

`Conflict {"exception":"[object] (Http\\Client\\Common\\Exception\\ClientErrorException(code: 409): Conflict at /app/vendor/php-http/client-common/src/Plugin/ErrorPlugin.php:83)`

I'm assuming the 409 relates to HTTP 409

## Steps to reproduce (as granular as possible, including screenshots where appropriate)

 1.  Attempt to create customer
 2.  Exception thrown
 3. 

## Logs

`Conflict {"exception":"[object] (Http\\Client\\Common\\Exception\\ClientErrorException(code: 409): Conflict at /app/vendor/php-http/client-common/src/Plugin/ErrorPlugin.php:83)`

## Example Payload

{"email":"colin@example.com","name":"Joe Doe ","companies":[{"id":19,"name":"Intercom Corp"}]}

## Postman Error

"code": "conflict",
"message": "Multiple existing users match this email address colin@example.com - must be more specific using user_id"

**Comment by GabrielAnca** [comment]
Hi @MCKLtech  👋 What API version you are using? You can find this in the [Developer Hub](https://app.intercom.com/a/apps/_/developer-hub) in the Basic information section of your app.

There was a similar limitation to what you mention in the Intercom API version 1.0 for the get users endpoint. I am not fully sure if that also affected the call you are making. Please ensure you are using version our API version 1.1 or higher. You can see the full explanation [in the API changelog](https://developers.intercom.com/building-apps/docs/api-changelog).

As this is related to the API rather than the PHP SDK, if the problem persists, I recommend you to use the [community](https://community.intercom.com/c/building-apps/rest-apis) or the Intercom messenger in the bottom right corner of the [Developer Hub](https://app.intercom.com/a/apps/_/developer-hub) to get support. They have the full context on the API and known issues and can help you better with specific API queries like this one.
