### ISSUE TITLE
Metadata cannot be blank for Event

### ISSUE THREAD

**Issue by FallDi** [intercom/intercom-php#81]
According https://doc.intercom.io/api/#event-metadata-types
I'm try to create Event using php
```
$intercom->createEvent(array(
  "event_name" => "placed-order",
  "created_at" => 1391691571,
  "user_id" => "314159",
  "metadata" => $more_metadata
));
```

If pass $more_metadata such as empty array []
In this case i got error Bad Request response from Intercom.

It not critical and I add if, but if you fix it will very fantastic =)

**Comment by dannyfallon** [comment]
I suspect the issue is the Intercom API is expecting a JSON object for the `metadata` field and Guzzle (the underlying framework) is not converting the empty array `[]` into an empty JSON object `{}` because it does not contain any data. Instead you're sending an empty array which we're throwing an error for. If you have no metadata then you should not set the `metadata` key in the array, it's not required.

**Comment by FallDi** [comment]
Yes, JSON_FORCE_OBJECT is nice solution, tnx! Yep, i'm currently not set metadata property if array is empty - it solve my problem.
